"""support lxns prober

迁移 ID: b5a52b0fbe82
父迁移: d095f6139db5
创建时间: 2025-08-03 16:30:57.870518

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b5a52b0fbe82'
down_revision: str | Sequence[str] | None = 'd095f6139db5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_maimai_updater_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prober_type', sa.Integer(), nullable=True))
        batch_op.alter_column('df_token',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_maimai_updater_user', schema=None) as batch_op:
        batch_op.alter_column('df_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('prober_type')

    # ### end Alembic commands ###
