"""init_db

迁移 ID: d095f6139db5
父迁移: 
创建时间: 2025-05-05 14:33:07.497722

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd095f6139db5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_maimai_updater_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_maimai_updater_token')),
    info={'bind_key': 'nonebot_plugin_maimai_updater'}
    )
    op.create_table('nonebot_plugin_maimai_updater_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sec_id', sa.String(), nullable=True),
    sa.Column('magic_id', sa.String(), nullable=True),
    sa.Column('friend_id', sa.String(), nullable=False),
    sa.Column('df_token', sa.String(), nullable=False),
    sa.Column('update_times', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_maimai_updater_user')),
    info={'bind_key': 'nonebot_plugin_maimai_updater'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_maimai_updater_user')
    op.drop_table('nonebot_plugin_maimai_updater_token')
    # ### end Alembic commands ###
