"""new bind logic

迁移 ID: da3b3de13229
父迁移: b5a52b0fbe82
创建时间: 2025-08-04 22:17:51.685606

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'da3b3de13229'
down_revision: str | Sequence[str] | None = 'b5a52b0fbe82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_maimai_updater_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lx_bound', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('df_bound', sa.Boolean(), nullable=True, insert_default=True))
        batch_op.drop_column('prober_type')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_maimai_updater_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prober_type', sa.INTEGER(), nullable=True))
        batch_op.drop_column('df_bound')
        batch_op.drop_column('lx_bound')

    # ### end Alembic commands ###
